In [2]:
import pandas as pd
import numpy as np
train=pd.read_csv("zomato.csv")
td=pd.DataFrame(train)
td

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
5,18189371,Din Tai Fung,162,Mandaluyong City,"Ground Floor, Mega Fashion Hall, SM Megamall, ...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056314,14.583764,Chinese,...,Botswana Pula(P),No,No,No,No,3,4.4,Green,Very Good,336
6,6300781,Buffet 101,162,Pasay City,"Building K, SM By The Bay, Sunset Boulevard, M...","SM by the Bay, Mall of Asia Complex, Pasay City","SM by the Bay, Mall of Asia Complex, Pasay Cit...",120.979667,14.531333,"Asian, European",...,Botswana Pula(P),Yes,No,No,No,4,4.0,Green,Very Good,520
7,6301290,Vikings,162,Pasay City,"Building B, By The Bay, Seaside Boulevard, Mal...","SM by the Bay, Mall of Asia Complex, Pasay City","SM by the Bay, Mall of Asia Complex, Pasay Cit...",120.979333,14.540000,"Seafood, Filipino, Asian, European",...,Botswana Pula(P),Yes,No,No,No,4,4.2,Green,Very Good,677
8,6300010,Spiral - Sofitel Philippine Plaza Manila,162,Pasay City,"Plaza Level, Sofitel Philippine Plaza Manila, ...","Sofitel Philippine Plaza Manila, Pasay City","Sofitel Philippine Plaza Manila, Pasay City, P...",120.980090,14.552990,"European, Asian, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.9,Dark Green,Excellent,621
9,6314987,Locavore,162,Pasig City,"Brixton Technology Center, 10 Brixton Street, ...",Kapitolyo,"Kapitolyo, Pasig City",121.056532,14.572041,Filipino,...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,532
10,6309903,Silantro Fil-Mex,162,Pasig City,"75 East Capitol Drive, Kapitolyo, Pasig City",Kapitolyo,"Kapitolyo, Pasig City",121.057916,14.567689,"Filipino, Mexican",...,Botswana Pula(P),No,No,No,No,3,4.9,Dark Green,Excellent,1070
11,6309455,Mad Mark's Creamery & Good Eats,162,Pasig City,"23 East Capitol Drive, Kapitolyo, Pasig City",Kapitolyo,"Kapitolyo, Pasig City",121.060820,14.570849,"American, Ice Cream, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.2,Green,Very Good,488
12,6318433,Silantro Fil-Mex,162,Quezon City,"Second Floor, UP Town Center, Katipunan Avenue...","UP Town Center, Diliman, Quezon City","UP Town Center, Diliman, Quezon City, Quezon City",121.075419,14.649503,"Filipino, Mexican",...,Botswana Pula(P),No,No,No,No,3,4.8,Dark Green,Excellent,294
13,6310470,Guevarra's,162,San Juan City,"387 P. Guevarra Corner Argonne Street, Additio...",Addition Hills,"Addition Hills, San Juan City",121.033592,14.593450,Filipino,...,Botswana Pula(P),Yes,No,No,No,3,4.2,Green,Very Good,458
14,6314605,Sodam Korean Restaurant,162,San Juan City,"17 J. Abad Santos Drive, Little Baguio, San Ju...",Little Baguio,"Little Baguio, San Juan City",121.038110,14.598890,Korean,...,Botswana Pula(P),No,No,No,No,3,4.3,Green,Very Good,223
15,18185059,Cafe Arabelle,162,Santa Rosa,"Ayala Mall, Solenad, Nuvali, Santa Rosa - Taga...","Nuvali, Don Jose, Santa Rosa","Nuvali, Don Jose, Santa Rosa, Santa Rosa",121.057040,14.237082,"Cafe, American, Italian, Filipino",...,Botswana Pula(P),No,No,No,No,3,3.6,Yellow,Good,29
16,18182702,Nonna's Pasta & Pizzeria,162,Santa Rosa,"Ground Floor, Building G, Solenad 3, Nuvali, D...","Solenad 3, Don Jose, Santa Rosa","Solenad 3, Don Jose, Santa Rosa, Santa Rosa",121.056587,14.237679,"Italian, Pizza",...,Botswana Pula(P),No,No,No,No,3,4.0,Green,Very Good,72
17,6318213,Balay Dako,162,Tagaytay City,"Aguinaldo Highway, Tagaytay City",Tagaytay City,"Tagaytay City, Tagaytay City",120.951589,14.101834,Filipino,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,211
18,18255654,Hobing Korean Dessert Cafe,162,Taguig City,"Third Floor, BGC Stopover Pavillion, Rizal Dri...","BGC Stopover Pavillion, Bonifacio Global City","BGC Stopover Pavillion, Bonifacio Global City,...",121.045878,14.554360,"Cafe, Korean, Desserts",...,Botswana Pula(P),No,No,No,No,2,4.5,Dark Green,Excellent,118
19,6308205,Wildflour Cafe + Bakery,162,Taguig City,"Ground Floor, Netlima Building, 4th Avenue Cor...",Bonifacio Global City,"Bonifacio Global City, Taguig City",121.046220,14.549337,"Cafe, Bakery, American, Italian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,392
20,6315438,NIU by Vikings,162,Taguig City,"Sixth Floor, SM Aura Premier, C5 Road Corner 2...","SM Aura Premier, Bonifacio Global City, Taguig...","SM Aura Premier, Bonifacio Global City, Taguig...",121.053725,14.545858,"Seafood, American, Mediterranean, Japanese",...,Botswana Pula(P),Yes,No,No,No,4,4.7,Dark Green,Excellent,535
21,6310406,The Food Hall by Todd English,162,Taguig City,"Fifth Floor, SM Aura Premier, C5 Corner 26th S...","SM Aura Premier, Bonifacio Global City, Taguig...","SM Aura Premier, Bonifacio Global City, Taguig...",121.053500,14.545655,"American, Asian, Italian, Seafood",...,Botswana Pula(P),Yes,No,No,No,4,4.5,Dark Green,Excellent,618
22,6600681,Chez Michou,30,Bras�_lia,"SCLN, 208, Bloco A, Loja 30, Asa Norte, Bras�_lia",Asa Norte,"Asa Norte, Bras�_lia",-47.881789,-15.764142,"Fast Food, French",...,Brazilian Real(R$),No,No,No,No,2,3.0,Orange,Average,6
23,6601005,Caf� Daniel Briand,30,Bras�_lia,"SCLN 104, Bloco A, Loja 26, Asa Norte, Bras�_lia",Asa Norte,"Asa Norte, Bras�_lia",-47.882667,-15.777500,Cafe,...,Brazilian Real(R$),No,No,No,No,1,3.8,Yellow,Good,9
24,6600292,Casa do Biscoito Mineiro,30,Bras�_lia,"SCLN 210, Bloco D, Loja 36/48, Asa Norte, Bras...",Asa Norte,"Asa Norte, Bras�_lia",-47.882136,-15.757472,Bakery,...,Brazilian Real(R$),No,No,No,No,2,3.7,Yellow,Good,11
25,6600441,Maori,30,Bras�_lia,"CLN 110, Bloco D, Loja 28, Asa Norte, Bras�_lia",Asa Norte,"Asa Norte, Bras�_lia",-47.888167,-15.758833,Brazilian,...,Brazilian Real(R$),No,No,No,No,3,3.8,Yellow,Good,11
26,6600970,Pizza �� Bessa,30,Bras�_lia,"SCS 214, Bloco C, Loja 40, Asa Sul, Bras�_lia",Asa Sul,"Asa Sul, Bras�_lia",-47.915667,-15.831167,Pizza,...,Brazilian Real(R$),No,No,No,No,2,3.2,Orange,Average,11
27,6600379,Sushi Loko,30,Bras�_lia,"SCS 213, Bloco C, Loja 35, Asa Sul, Bras�_lia",Asa Sul,"Asa Sul, Bras�_lia",-47.915667,-15.831000,Japanese,...,Brazilian Real(R$),No,No,No,No,3,3.1,Orange,Average,10
28,6600214,Beirute,30,Bras�_lia,"CLS 109, Bloco A, Loja 2/6, Asa Sul, Bras�_lia",Asa Sul,"Asa Sul, Bras�_lia",-47.907500,-15.820000,Arabian,...,Brazilian Real(R$),No,No,No,No,3,3.7,Yellow,Good,8
29,6601218,New Koto,30,Bras�_lia,"SCS 212, Bloco B, Loja 26, Asa Sul, Bras�_lia",Asa Sul,"Asa Sul, Bras�_lia",-47.910167,-15.827333,Japanese,...,Brazilian Real(R$),No,No,No,No,4,3.7,Yellow,Good,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4469,18198467,Dessert in Desert,1,New Delhi,"21-UB, Jawahar Nagar, Kamla Nagar, New Delhi",Kamla Nagar,"Kamla Nagar, New Delhi",77.206698,28.681964,"Cafe, Fast Food, Desserts",...,Indian Rupees(Rs.),No,No,No,No,1,3.4,Orange,Average,38
4470,311903,Domino's Pizza,1,New Delhi,"Ground Floor, 29/4, Nangia Park, Shakti Nagar...",Kamla Nagar,"Kamla Nagar, New Delhi",77.195376,28.679401,"Pizza, Fast Food",...,Indian Rupees(Rs.),No,No,No,No,2,3.4,Orange,Average,36
4471,18458665,Filmy Cafe & Bar,1,New Delhi,"4/3, 1st Floor, Roop Nagar, Near Kamla Nagar M...",Kamla Nagar,"Kamla Nagar, New Delhi",77.201218,28.683500,"North Indian, Fast Food, Chinese, Continental",...,Indian Rupees(Rs.),Yes,No,No,No,3,2.9,Orange,Average,4
4472,6651,Firenze,1,New Delhi,"6, 38 Bungalow Road, Kamla Nagar, New Delhi",Kamla Nagar,"Kamla Nagar, New Delhi",77.204844,28.683960,Cafe,...,Indian Rupees(Rs.),No,No,No,No,2,2.8,Orange,Average,25
4473,311076,Giani,1,New Delhi,"30/26, Near Nangia Park, Shakti Nagar, Kamla N...",Kamla Nagar,"Kamla Nagar, New Delhi",77.195525,28.680104,"Ice Cream, Desserts",...,Indian Rupees(Rs.),No,Yes,No,No,1,3.4,Orange,Average,41
4474,9001,Gullu's,1,New Delhi,"2, Main Road, Malka Ganj, Kamla Nagar, New Delhi",Kamla Nagar,"Kamla Nagar, New Delhi",77.207839,28.677097,"North Indian, Mughlai",...,Indian Rupees(Rs.),No,No,No,No,2,3.1,Orange,Average,69
4475,8995,Manwhar,1,New Delhi,"5, Roop Nagar, Shakti Nagar Chowk, Kamla Nagar...",Kamla Nagar,"Kamla Nagar, New Delhi",77.198289,28.681938,"South Indian, North Indian, Chinese",...,Indian Rupees(Rs.),No,No,No,No,2,3.2,Orange,Average,69
4476,18489508,Midnight Hunger Hub,1,New Delhi,"Kamla Nagar, New Delhi",Kamla Nagar,"Kamla Nagar, New Delhi",0.000000,0.000000,"North Indian, Fast Food, Italian, Asian",...,Indian Rupees(Rs.),No,No,No,No,2,3.3,Orange,Average,6
4477,7689,Mini Shop,1,New Delhi,"1, UB, Opposite KM College, Bunglow Road, Kaml...",Kamla Nagar,"Kamla Nagar, New Delhi",77.206428,28.682475,"Fast Food, Beverages",...,Indian Rupees(Rs.),No,No,No,No,1,3.3,Orange,Average,49
4478,307959,Nine 75 Lounge & Bar,1,New Delhi,"B-49, Kamla Nagar Main Road, Kamla Nagar, New ...",Kamla Nagar,"Kamla Nagar, New Delhi",77.200480,28.682621,"Chinese, North Indian, Italian, Continental, F...",...,Indian Rupees(Rs.),Yes,No,No,No,2,3.2,Orange,Average,145
4479,18222571,Pradhan Ji Multi Cuisine Restaurant,1,New Delhi,"32-UB, Lower Ground Floor, Jawahar Nagar, Kaml...",Kamla Nagar,"Kamla Nagar, New Delhi",77.207371,28.680862,"North Indian, Chinese, Continental",...,Indian Rupees(Rs.),No,Yes,No,No,2,3.3,Orange,Average,41
4480,310202,Punjabi Chaap Corner,1,New Delhi,"E-146, Near Incense Showroom, Kamla Nagar, New...",Kamla Nagar,"Kamla Nagar, New Delhi",77.205081,28.682167,North Indian,...,Indian Rupees(Rs.),No,Yes,No,No,1,2.9,Orange,Average,15
4481,301470,Sagar Ratna,1,New Delhi,"115-A, Ground Floor, Kamla Nagar, New Delhi",Kamla Nagar,"Kamla Nagar, New Delhi",77.198684,28.681658,"South Indian, North Indian, Chinese",...,Indian Rupees(Rs.),No,Yes,No,No,2,2.7,Orange,Average,109
4482,5433,Shiva Coffee & South Indian Fast Food,1,New Delhi,"1-D, Kamla Nagar, New Delhi",Kamla Nagar,"Kamla Nagar, New Delhi",77.199757,28.682385,South Indian,...,Indian Rupees(Rs.),No,No,No,No,1,2.7,Orange,Average,41
4483,18349733,The Ice Cafe,1,New Delhi,"25-UB, Jawahar Nagar, Kamla Nagar, New Delhi",Kamla Nagar,"Kamla Nagar, New Delhi",77.206959,28.681598,"Cafe, Chinese, Continental, Italian, Desserts,...",...,Indian Rupees(Rs.),No,No,No,No,1,3.2,Orange,Average,28
4484,18421019,Tikka Junction,1,New Delhi,"Shop G 2, Vardhaman City Centre, Near Shakti N...",Kamla Nagar,"Kamla Nagar, New Delhi",77.189055,28.678008,"North Indian, Chinese",...,Indian Rupees(Rs.),No,No,No,No,2,3.4,Orange,Average,21
4485,18317510,Trending Eats,1,New Delhi,"23,Sai Dhaam PG,Bungalow Road,Block UA,Jawahar...",Kamla Nagar,"Kamla Nagar, New Delhi",77.208495,28.679896,"Italian, Fast Food",...,Indian Rupees(Rs.),No,No,No,No,2,3.4,Orange,Average,21
4486,303104,Twenty Four Seven,1,New Delhi,"23, Opposite Hansraj Hostel, Kamla Nagar, New ...",Kamla Nagar,"Kamla Nagar, New Delhi",77.208045,28.678689,"Fast Food, North Indian",...,Indian Rupees(Rs.),No,No,No,No,1,3.3,Orange,Average,53
4487,8991,Vikrant Cafe,1,New Delhi,"13-A, Kamla Nagar, New Delhi",Kamla Nagar,"Kamla Nagar, New Delhi",77.199953,28.679932,"South Indian, North Indian",...,Indian Rupees(Rs.),No,Yes,No,No,2,3.3,Orange,Average,145
4488,6662,Vishal Restaurant,1,New Delhi,"5122, Building Harphool Singh, Clock Tower, Su...",Kamla Nagar,"Kamla Nagar, New Delhi",77.202925,28.675602,North Indian,...,Indian Rupees(Rs.),No,No,No,No,2,3.1,Orange,Average,24
4489,18365889,Badri Prasad Ramesh Kumar Caterers,1,New Delhi,"66-67/E, Near Chota Gali Chakkar, Kamla Nagar,...",Kamla Nagar,"Kamla Nagar, New Delhi",77.203469,28.682646,North Indian,...,Indian Rupees(Rs.),No,No,No,No,1,3.5,Yellow,Good,12
4490,18245268,Bistro,1,New Delhi,"Jawahar Nagar, Kamla Nagar, New Delhi",Kamla Nagar,"Kamla Nagar, New Delhi",77.207506,28.680698,Beverages,...,Indian Rupees(Rs.),No,No,No,No,1,3.9,Yellow,Good,55
4491,309856,Chaudhary Sweets Corner,1,New Delhi,"10/18, Shakti Nagar, Near Roshanara Club, Kaml...",Kamla Nagar,"Kamla Nagar, New Delhi",77.196349,28.677217,"Desserts, Beverages",...,Indian Rupees(Rs.),No,No,No,No,1,3.8,Yellow,Good,36
4492,309604,Chowringhee,1,New Delhi,"16 UB, Jawahar Nagar, Bungalow Road, Kamla Nag...",Kamla Nagar,"Kamla Nagar, New Delhi",77.207444,28.681003,"Fast Food, Beverages",...,Indian Rupees(Rs.),No,Yes,No,No,1,3.6,Yellow,Good,108
4493,18332062,Cones & Curries,1,New Delhi,"Shop 28, Jawahar Nagar, Opposite Hansraj Boys ...",Kamla Nagar,"Kamla Nagar, New Delhi",77.208375,28.680111,Fast Food,...,Indian Rupees(Rs.),No,Yes,No,No,1,3.7,Yellow,Good,151
4494,6658,Darvesh Corner,1,New Delhi,"7673, Birla Lane, Clock Tower, Near Amba Cinem...",Kamla Nagar,"Kamla Nagar, New Delhi",77.201128,28.678744,North Indian,...,Indian Rupees(Rs.),No,No,No,No,2,3.6,Yellow,Good,91
4495,9644,Deez Biryani & Kebabs,1,New Delhi,"4/3, 1st Floor, Roop Nagar, Near Kamla Nagar M...",Kamla Nagar,"Kamla Nagar, New Delhi",77.201218,28.683500,"Biryani, North Indian, Mughlai",...,Indian Rupees(Rs.),No,Yes,No,No,2,3.7,Yellow,Good,393
4496,18349974,Frozen Pan,1,New Delhi,"Shop PVT 3, Ground Floor, Block UB, Jawahar Na...",Kamla Nagar,"Kamla Nagar, New Delhi",77.207386,28.680921,"Ice Cream, Fast Food, Beverages",...,Indian Rupees(Rs.),No,No,No,No,1,3.9,Yellow,Good,72
4497,2267,Giani's,1,New Delhi,"28 UA, Main Bungalow Road, Jawahar Nagar, Kaml...",Kamla Nagar,"Kamla Nagar, New Delhi",77.208294,28.679990,"Ice Cream, Desserts",...,Indian Rupees(Rs.),No,Yes,No,No,1,3.8,Yellow,Good,167
4498,18377630,Havmor Ice Cream,1,New Delhi,"5885, 28-UA, Ground Floor, Jawajar Agar, Civil...",Kamla Nagar,"Kamla Nagar, New Delhi",77.208315,28.679521,Ice Cream,...,Indian Rupees(Rs.),No,Yes,No,No,1,3.7,Yellow,Good,20

In [5]:
from sklearn import preprocessing
x=preprocessing.LabelEncoder()
for col in td.columns:
    td[col]=x.fit_transform(td[col])
    print(td[col])

0       2309
1       2299
2       2295
3       2312
4       2305
5       3005
6       2297
7       2298
8       2296
9       2307
10      2302
11      2301
12      2311
13      2304
14      2306
15      3004
16      3003
17      2310
18      3175
19      2300
20      2308
21      2303
22      2321
23      2323
24      2317
25      2320
26      2322
27      2318
28      2316
29      2325
        ...
4469    3008
4470    1840
4471    4284
4472     593
4473    1777
4474     792
4475     791
4476    4470
4477     693
4478    1514
4479    3051
4480    1704
4481    1120
4482     513
4483    3508
4484    3980
4485    3405
4486    1208
4487     790
4488     595
4489    3649
4490    3133
4491    1685
4492    1654
4493    3427
4494     594
4495     831
4496    3520
4497     243
4498    3709
Name: Restaurant ID, Length: 4499, dtype: int64
0       1926
1       1635
2       1484
3       2403
4       2805
5       1063
6        510
7       3613
8       3036
9       1951
10      2945
11      2000
12      2945
13      1419
14      2987
15       559
16      2349
17       285
18      1506
19      3667
20      2267
21      3315
22       756
23       618
24       667
25      2065
26      2542
27      3100
28       336
29      2314
        ...
4469    1024
4470    1074
4471    1198
4472    1205
4473    1348
4474    1425
4475    2063
4476    2127
4477    2140
4478    2340
4479    2562
4480    2591
4481    2784
4482    2896
4483    3355
4484    3478
4485    3515
4486    3532
4487    3614
4488    3624
4489     257
4490     420
4491     727
4492     833
4493     882
4494     965
4495     986
4496    1302
4497    1349
4498    1478
Name: Restaurant Name, Length: 4499, dtype: int64
0       4
1       4
2       4
3       4
4       4
5       4
6       4
7       4
8       4
9       4
10      4
11      4
12      4
13      4
14      4
15      4
16      4
17      4
18      4
19      4
20      4
21      4
22      2
23      2
24      2
25      2
26      2
27      2
28      2
29      2
       ..
4469    0
4470    0
4471    0
4472    0
4473    0
4474    0
4475    0
4476    0
4477    0
4478    0
4479    0
4480    0
4481    0
4482    0
4483    0
4484    0
4485    0
4486    0
4487    0
4488    0
4489    0
4490    0
4491    0
4492    0
4493    0
4494    0
4495    0
4496    0
4497    0
4498    0
Name: Country Code, Length: 4499, dtype: int64
0       60
1       60
2       61
3       61
4       61
5       61
6       78
7       78
8       78
9       79
10      79
11      79
12      87
13      90
14      90
15      91
16      91
17      97
18      98
19      98
20      98
21      98
22      16
23      16
24      16
25      16
26      16
27      16
28      16
29      16
        ..
4469    74
4470    74
4471    74
4472    74
4473    74
4474    74
4475    74
4476    74
4477    74
4478    74
4479    74
4480    74
4481    74
4482    74
4483    74
4484    74
4485    74
4486    74
4487    74
4488    74
4489    74
4490    74
4491    74
4492    74
4493    74
4494    74
4495    74
4496    74
4497    74
4498    74
Name: City, Length: 4499, dtype: int64
0       4099
1       2853
2       2298
3       4103
4       4102
5       2573
6       2040
7       2039
8       3298
9       2032
10      1553
11       681
12      3571
13      1139
14       437
15      1878
16      2540
17      1829
18      4098
19      2575
20      4032
21      2347
22      3477
23      3475
24      3476
25      2109
26      3541
27      3540
28      2110
29      3539
        ...
4469     639
4470    2526
4471    1196
4472    1430
4473     984
4474     578
4475    1320
4476    2804
4477      29
4478    1939
4479    1050
4480    2260
4481     174
4482      35
4483     753
4484    3989
4485     691
4486     690
4487     270
4488    1358
4489    1493
4490    2756
4491      61
4492     391
4493    3794
4494    1564
4495    1196
4496    4011
4497     861
4498    1414
Name: Address, Length: 4499, dtype: int64
0       120
1       423
2       233
3       561
4       561
5       561
6       562
7       562
8       636
9       383
10      383
11      383
12      688
13        9
14      422
15      484
16      638
17      656
18       63
19       98
20      560
21      560
22       51
23       51
24       51
25       51
26       52
27       52
28       52
29       52
       ...
4469    381
4470    381
4471    381
4472    381
4473    381
4474    381
4475    381
4476    381
4477    381
4478    381
4479    381
4480    381
4481    381
4482    381
4483    381
4484    381
4485    381
4486    381
4487    381
4488    381
4489    381
4490    381
4491    381
4492    381
4493    381
4494    381
4495    381
4496    381
4497    381
4498    381
Name: Locality, Length: 4499, dtype: int64
0       121
1       430
2       239
3       569
4       569
5       569
6       570
7       570
8       657
9       389
10      389
11      389
12      710
13        9
14      429
15      491
16      659
17      677
18       64
19       99
20      568
21      568
22       51
23       51
24       51
25       51
26       52
27       52
28       52
29       52
       ...
4469    387
4470    387
4471    387
4472    387
4473    387
4474    387
4475    387
4476    387
4477    387
4478    387
4479    387
4480    387
4481    387
4482    387
4483    387
4484    387
4485    387
4486    387
4487    387
4488    387
4489    387
4490    387
4491    387
4492    387
4493    387
4494    387
4495    387
4496    387
4497    387
4498    387
Name: Locality Verbose, Length: 4499, dtype: int64
0       3825
1       3824
2       3836
3       3833
4       3838
5       3832
6       3822
7       3821
8       3823
9       3834
10      3839
11      3840
12      3841
13      3826
14      3827
15      3837
16      3835
17      3820
18      3828
19      3829
20      3831
21      3830
22       451
23       449
24       450
25       447
26       442
27       442
28       444
29       443
        ...
4469    2292
4470    2127
4471    2160
4472    2244
4473    2128
4474    2318
4475    2150
4476     495
4477    2289
4478    2157
4479    2306
4480    2253
4481    2152
4482    2155
4483    2297
4484    2062
4485    2334
4486    2321
4487    2156
4488    2180
4489    2185
4490    2309
4491    2130
4492    2308
4493    2329
4494    2158
4495    2160
4496    2307
4497    2327
4498    2328
Name: Longitude, Length: 4499, dtype: int64
0        226
1        224
2        230
3        233
4        232
5        231
6        218
7        219
8        223
9        229
10       227
11       228
12       236
13       234
14       235
15       216
16       217
17       215
18       225
19       222
20       221
21       220
22        80
23        79
24        82
25        81
26        70
27        71
28        74
29        72
        ...
4469    3435
4470    3397
4471    3446
4472    3448
4473    3403
4474    3380
4475    3434
4476      84
4477    3440
4478    3441
4479    3420
4480    3437
4481    3429
4482    3439
4483    3428
4484    3384
4485    3399
4486    3393
4487    3401
4488    3369
4489    3442
4490    3417
4491    3381
4492    3423
4493    3404
4494    3394
4495    3446
4496    3422
4497    3402
4498    3398
Name: Latitude, Length: 4499, dtype: int64

TypeError: '<' not supported between instances of 'float' and 'str'

In [6]:
td.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4499 entries, 0 to 4498
Data columns (total 21 columns):
Restaurant ID           4499 non-null int64
Restaurant Name         4499 non-null int64
Country Code            4499 non-null int64
City                    4499 non-null int64
Address                 4499 non-null int64
Locality                4499 non-null int64
Locality Verbose        4499 non-null int64
Longitude               4499 non-null int64
Latitude                4499 non-null int64
Cuisines                4490 non-null object
Average Cost for two    4499 non-null int64
Currency                4499 non-null object
Has Table booking       4499 non-null object
Has Online delivery     4499 non-null object
Is delivering now       4499 non-null object
Switch to order menu    4499 non-null object
Price range             4499 non-null int64
Aggregate rating        4499 non-null float64
Rating color            4499 non-null object
Rating text             4499 non-null object
Votes                   4499 non-null int64
dtypes: float64(1), int64(12), object(8)
memory usage: 738.2+ KB

In [1]:
#num=['Restaurant Name','City','Address','Locality','Locality Verbose','Cuisines','Currency','Has Table booking','Has Online delivery','Is delivering now','Switch to order menu','Rating color','Rating text']
#=train[list(num)].values
#print(pd.to_numeric(x, errors='coerce'))
#train.City=train.City.astype(float)

In [7]:
td.dtypes

Restaurant ID             int64
Restaurant Name           int64
Country Code              int64
City                      int64
Address                   int64
Locality                  int64
Locality Verbose          int64
Longitude                 int64
Latitude                  int64
Cuisines                 object
Average Cost for two      int64
Currency                 object
Has Table booking        object
Has Online delivery      object
Is delivering now        object
Switch to order menu     object
Price range               int64
Aggregate rating        float64
Rating color             object
Rating text              object
Votes                     int64
dtype: object

In [9]:
td.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [12]:
td.describe()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,4499.00000,4499.000000,4499.00000,4499.000000,4499.000000,4499.000000,4499.000000,4499.000000,4499.000000,4499.000000,4499.000000,4499.000000,4499.000000
mean,2249.00000,1842.337631,0.83174,56.314737,2138.897088,340.083352,347.993110,1879.179818,1973.623916,611.534341,1.938653,2.982285,226.944210
std,1298.89376,1076.542074,2.18455,22.821072,1206.278978,201.606373,207.027168,1099.676452,1224.985535,606.522494,0.928175,1.387997,560.646907
min,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,1124.50000,903.500000,0.00000,41.000000,1106.500000,187.000000,193.000000,906.500000,901.500000,250.000000,1.000000,2.800000,10.000000
50%,2249.00000,1822.000000,0.00000,73.000000,2187.000000,294.000000,301.000000,1862.000000,1971.000000,450.000000,2.000000,3.400000,52.000000
75%,3373.50000,2776.500000,0.00000,74.000000,3158.500000,532.500000,539.500000,2800.500000,3026.500000,750.000000,3.000000,3.800000,197.000000
max,4498.00000,3741.000000,7.00000,109.000000,4221.000000,743.000000,766.000000,3863.000000,4123.000000,7000.000000,4.000000,4.900000,10934.000000

In [14]:
td['Restaurant Name'].value_counts()

566     37
1074    31
2090    25
3065    24
308     21
1401    16
1098    14
2784    13
2536    13
1449    12
1349    12
1791    12
3053    12
314     11
1348    11
321     10
899     10
686     10
2514    10
1296     9
2210     9
3636     8
1711     8
2707     7
525      7
2159     7
2915     6
333      6
1755     6
523      6
        ..
3115     1
3171     1
3175     1
1182     1
1158     1
3227     1
1178     1
3223     1
1174     1
3219     1
1170     1
3215     1
1166     1
3211     1
1162     1
3207     1
3203     1
1130     1
1154     1
3199     1
1150     1
3195     1
1146     1
1142     1
3187     1
1138     1
3183     1
1134     1
3179     1
0        1
Name: Restaurant Name, Length: 3742, dtype: int64

In [15]:
td.isnull().any()

Restaurant ID           False
Restaurant Name         False
Country Code            False
City                    False
Address                 False
Locality                False
Locality Verbose        False
Longitude               False
Latitude                False
Cuisines                 True
Average Cost for two    False
Currency                False
Has Table booking       False
Has Online delivery     False
Is delivering now       False
Switch to order menu    False
Price range             False
Aggregate rating        False
Rating color            False
Rating text             False
Votes                   False
dtype: bool

In [17]:
td.fillna(0,inplace=True)